### ISSUE TITLE
Make changes to review time and sorting

### ISSUE THREAD

**Issue by AriesOdyssey** [prncc/obsidian-repeat-plugin#19]
Hi, I'd like to change the code for myself such that the time of day does not matter. (So if I reviewed a note at 23:00 on a Saturday, I could review it again on 00:00 or 00:01 which is Sunday, instead of that the note only comes available after Sunday 23:00 to review/repeat again). I have looked at your code but have not been able to find the right part to change. 

Another thing that would be nice is the note order getting randomized every day. Because if you don't randomize you keep seeing them in the same order if you incremented multiple notes by the same time.

I am a beginner coder so any help is appreciated!

**Comment by prncc** [comment]
Hi AriesOdyssey,

The next-day repeat behavior you're looking for is (almost) already in the plugin. The only difference is that it will become due again at 06:00 instead of 00:00. 

6AM is defined here: https://github.com/prncc/obsidian-repeat-plugin/blob/master/src/repeat/choices.ts#L7

To change the time for yourself only, you could git clone this repo into your plugins folder (that would be .obsidian/plugins/obsidian-repeat-plugin under your vault folder). Then modify the code there and `yarn build` (reload obsidian with the "reload without saving" command). 

This could be a setting though, which would entail adding the setting, and reading it wherever the current constant is used.

---

For randomization, you you shuffle the notes due returned here: https://github.com/prncc/obsidian-repeat-plugin/blob/master/src/repeat/queries.ts#L49 and then return .first() after shuffling. I'm not sure if there'd be some side-effects elsewhere, maybe you can let me know after testing. Ultimately though, repeat times would still get incremented together. 

If you decide you want to work on one of these separately, please create a new issue for each change so we can discuss it. Cheers
